### ISSUE TITLE
Steem Social - SteemIt Social Media Hub - Logo Request

### ISSUE THREAD

**Issue by ivannewgate89** [severinolorillajr/steemsocial#1]
can input a steemit logo? )

**Comment by severinolorillajr** [comment]
Of course. I would greatly appreciate.
Just please take note of the requirements and the Utopian submission dates so you can get rewarded accordingly.
Thanks and looking forward for your contribution.
Cheers!

**Comment by ivannewgate89** [comment]
okay, thanks ) Cheers!!!

2018-03-30 1:23 GMT+07:00 Severino Lorilla Jr. <notifications@github.com>:

**Comment by ivannewgate89** [comment]
my link for utopian logo steem social
https://utopian.io/utopian-io/@ivannewgate89/logo-for-steem-social-steemit-social-media-hub
thanks

2018-03-30 12:07 GMT+07:00 Irvan Newgate <irvan.newgate89@gmail.com>:

**Comment by severinolorillajr** [comment]
Hi, 
Thanks for your support to Steem Social.
However, I have already selected a logo.
Great work.
Cheers!

**Comment by ivannewgate89** [comment]
2018-04-05 9:11 GMT+07:00 Severino Lorilla Jr. <notifications@github.com>:

**Comment by ivannewgate89** [comment]
okay, no problem )
thanks to for support
Cheers!!!

2018-04-05 9:11 GMT+07:00 Severino Lorilla Jr. <notifications@github.com>:

**Comment by ivannewgate89** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/2a494220fe",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Irvan is tired of keeping Fiverr a secret.
    

    
        Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    

If you would like to unsubscribe and stop receiving these emails click here.

**Comment by ivannewgate89** [comment]
Fiverr
    
    
            
      {
          "@context": "http://schema.org",
          "@type": "EmailMessage",
          "action": {
            "@type": "ViewAction",
            "url": "https://www.fiverr.com/s2/981920e887",
            "name": "Browse Services on Fiverr"
          },
          "description": "Browse Services on Fiverr"
      }
    

        
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    

                                        
    

    
        Irvan is tired of keeping Fiverr a secret.
    

    
        Fiverr is the world’s largest marketplace for services,where you can get everything you need at an unbeatable value.
    

    
        Sounds too good to be true? See for yourself!
    



                                        
                                            
                                                
                                                    
                                                        
                                                            Browse Services On Fiverr
                                                        
                                                    
                                                
                                                
                                                    
                                                        

		
			
			
			The Fiverr Team
		
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
                
                    
                        
                            
                                

                                    © Fiverr International Limited 2010-2016, Fiverr Inc. | 401 Broadway, Suite 1600 New York NY, 10013 USA.
                                    Your personal information will not be stored or used for any marketing purposes.
                                
                            
                         
                    
                
            
        
            

    

If you would like to unsubscribe and stop receiving these emails click here.
