### ISSUE TITLE
Logo for task reguest SteemSocial

### ISSUE THREAD

**Issue by familqasimov** [severinolorillajr/steemsocial#2]
Hi sir. I've created a logo that suits your task request. I believe you will like it. Simple and attractive. Before I share it, I would like to know your thoughts. Thank you.

![steem social](https://user-images.githubusercontent.com/36432269/38168153-c9c2ad24-3555-11e8-936a-ca08148f832b.png)

**Comment by severinolorillajr** [comment]
Hi, 
Thanks for your support to Steem Social.
However, I have already selected a logo.
Great work.
Cheers!
