### ISSUE TITLE
Steem Social Logo Design

### ISSUE THREAD

**Issue by berkorasen** [severinolorillajr/steemsocial#3]
Hi, ı sharde this design to you 3 days ago. Do you want am i change something on this logo?
Do you like that? If you like it ı can share this logo on utopian.

![usteeej7-1](https://user-images.githubusercontent.com/37547531/38176882-bbab9a3e-35ff-11e8-8824-c2df236a82ca.jpg)
![untitled-1](https://user-images.githubusercontent.com/37547531/38176883-bf982bd0-35ff-11e8-897a-ce56bfdc84eb.jpg)
![unxcxtitled-1](https://user-images.githubusercontent.com/37547531/38176884-c1b67066-35ff-11e8-87d6-fe3225d77f90.jpg)

**Comment by berkorasen** [comment]
https://utopian.io/utopian-io/@berkorasen/logo-design-proposal-for-steem-social

**Comment by berkorasen** [comment]
I shared my design for your task.

**Comment by severinolorillajr** [comment]
Hi, 
Thanks for your support to Steem Social.
However, I have already selected a logo.
Great work.
Cheers!
