### ISSUE TITLE
Steem Social Logo Proposal

### ISSUE THREAD

**Issue by dibon-github** [severinolorillajr/steemsocial#4]
![steem-social](https://user-images.githubusercontent.com/31919065/38178822-69590f66-364d-11e8-9f67-bd30390baa4d.jpg)
![variations](https://user-images.githubusercontent.com/31919065/38178823-69a7b832-364d-11e8-931a-b3fba3c641df.jpg)

**Comment by dibon-github** [comment]
You can suggest sir, if you want something to be changed

**Comment by severinolorillajr** [comment]
Hi, 
Thanks for your support to Steem Social.
However, I have already selected a logo.
Great work.
Cheers!
